// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASwDjQDUL2LZyobAzptGfHUaKUfGc8mlw',
    appId: '1:453854742109:android:274a5f3499c1d715edefb4',
    messagingSenderId: '453854742109',
    projectId: 'test1140526',
    databaseURL: 'https://test1140526-default-rtdb.firebaseio.com',
    storageBucket: 'test1140526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBU68sd4fYkPRAAoOEFyq4XLbRwpxrNQE',
    appId: '1:453854742109:ios:9e8344d03c46b188edefb4',
    messagingSenderId: '453854742109',
    projectId: 'test1140526',
    databaseURL: 'https://test1140526-default-rtdb.firebaseio.com',
    storageBucket: 'test1140526.firebasestorage.app',
    androidClientId: '453854742109-rjq6hh1nv1h90adfeurtfaerfitq4olu.apps.googleusercontent.com',
    iosBundleId: 'com.example.storage1140609',
  );
}
